import { Box, Typography } from "@mui/material";

export default function ReturnPolicy() {
  return (
    <Box
      sx={{
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        maxWidth: { xs: "95%", md: "80%" },
        mx: "auto",
        py: 5,
        color: "#c6c8cc",
      }}
    >
      <Box mb={5} textAlign="center">
        <Typography variant="h5" fontSize="22px" fontWeight="800" gutterBottom>
          Return & Refund Policy
        </Typography>
        <Typography variant="body1" fontSize="13px" fontWeight="400">
          Updated at 2025-01-01
        </Typography>
      </Box>
      <Box mb={5} > 
        <Typography variant="h6" fontSize="16Px" gutterBottom fontWeight="800">
          Definitions and key terms
        </Typography>
        <Typography variant="body1" fontSize="15px" gutterBottom>
          To help explain things as clearly as possible in this Return & Refund
          Policy, every time any of these terms are referenced, are strictly
          defined as:
        </Typography>
        <Box component="ul" sx={{ pl: 5 }}>
          <Typography component="li" variant="body1" gutterBottom>
        Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
          </Typography>
          <Typography component="li" variant="body1" gutterBottom>
           Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Shadow Games, that is responsible for your information under this Return & Refund Policy.
          </Typography>
          <Typography component="li" variant="body1" gutterBottom>
          Customer: refers to the company, organization or person that signs up to use the Shadow Games Service to manage the relationships with your consumers or service users.

          </Typography>
          <Typography component="li" variant="body1" gutterBottom>
          Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Shadow Games and use the services.
          </Typography>
          <Typography component="li" variant="body1" gutterBottom>
         Service: refers to the service provided by Shadow Games as described in the relative terms (if available) and on this platform.
          </Typography>
          <Typography component="li" variant="body1" gutterBottom>
            Website: site, which can be accessed via this URL:{" "}
            <Typography component="span" sx={{ color: "#0669b2" }}>
              <a
                href="https://shadowgames.in"
                target="_blank"
                rel="noopener noreferrer"
                style={{ color: "#0669b2", textDecoration: "underline" }}
              >
                https://shadowgames.in
              </a>
            </Typography>
          </Typography>
          <Typography component="li" variant="body1" gutterBottom>
            You: a person or entity registered with Shadow Games to use the
            Services.
          </Typography>
        </Box>
       
      </Box>
        <Box >
            <Typography variant="h6" fontSize="16Px" gutterBottom fontWeight="800">
            Return & Refund Policy
            </Typography>
        </Box> 
        
    </Box>
  );
}
